### ISSUE TITLE
Monitoring: timestamp shouldn't decrease

### ISSUE THREAD

**Issue by e-lo** [MobilityData/gtfs-realtime-validator#135]
### Relevant [Best Practice](https://gtfs.org/realtime/best-practices/) text:
> Timestamp should not decrease between two sequential feed iterations.

**Comment by barbeau** [comment]
@e-lo I believe this is covered by:
https://github.com/MobilityData/gtfs-realtime-validator/blob/master/RULES.md#E018

**Comment by e-lo** [comment]
Closed as duplicate
