### ISSUE TITLE
Docker image push to GitHub Container Registry is failing

### ISSUE THREAD

**Issue by barbeau** [MobilityData/gtfs-realtime-validator#150]
**Summary:** 

It looks like starting on April 20th the Docker image push to the GitHub Container registry started failing with:

```
Run docker/login-action@v1
  with:
    registry: ghcr.io
    username: MobilityData
    password: ***
    ecr: auto
    logout: true
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.15-10/x64
Logging into ghcr.io...
Error: Error response from daemon: Get "https://ghcr.io/v[2](https://github.com/MobilityData/gtfs-realtime-validator/runs/6296741109?check_suite_focus=true#step:7:2)/": denied: denied
```

Example of failed job:
https://github.com/MobilityData/gtfs-realtime-validator/runs/6296741109?check_suite_focus=true

@maximearmstrong Do you know if the GitHub credentials for MobilityData would have changed in this timeframe?

**Steps to reproduce:** 

Merge a PR to the main branch to trigger the dockery.yml file to run as a GitHub Action

**Expected behavior:** 

Docker image should publish to the GitHub Container Registry

**Observed behavior:** 

Looks like the login process is failing

**Platform:** 

GitHub Action

**Comment by maximearmstrong** [comment]
@barbeau I'm not aware of any changes. It looks like the token is not valid anymore. Do you know who owns the PAT?

**Comment by barbeau** [comment]
I believe PAT belonged to @lionel-nj.
