### ISSUE TITLE
Snapshot jar not available

### ISSUE THREAD

**Issue by NVBWcho** [MobilityData/gtfs-realtime-validator#185]
The jar mentioned on https://github.com/MobilityData/gtfs-realtime-validator/packages/1268975 with
<dependency>
  <groupId>org.mobilitydata</groupId>
  <artifactId>gtfs-realtime-validator-webapp</artifactId>
  <version>1.0.0-SNAPSHOT</version>
</dependency>
is no longer availalbe. 
For example, mvn compile leads to the following error:

 Could not resolve dependencies for project org.example:realtimevalidator:jar:1.0-SNAPSHOT: The following artifacts coul
d not be resolved: org.mobilitydata:gtfs-realtime-validator-webapp:jar:1.0.0-SNAPSHOT (absent): Could not find artifact org.mobilitydata:gtfs-realtime-validator-webapp:jar:1.0.0-SN
APSHOT -> [Help 1]

**Comment by civiliaInc** [comment]
Hello, may you please describe how you managed to retrieve the jar? Following the procedure ended with:
openjdk version "21.0.4" 2024-07-16

pom.xml :

<dependency>
  <groupId>org.mobilitydata</groupId>
  <artifactId>gtfs-realtime-validator-webapp</artifactId>
  <version>1.0.0-SNAPSHOT</version>
</dependency>

mvn install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Malformed POM /home/xavier/Documents/Civilia/projets/testedTools/gtfs-realtime-validator/pom.xml: Expected root element 'project' but found 'dependency' (position: START_TAG seen <dependency>... @1:13)  @ /home/xavier/Documents/Civilia/projets/testedTools/gtfs-realtime-validator/pom.xml, line 1, column 13
[ERROR] 'modelVersion' is missing. @ line 1, column 13
[ERROR] 'modelVersion' is missing. @ line 1, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.mobilitydata:gtfs-realtime-validator-webapp:1.0.0-SNAPSHOT (/home/xavier/Documents/Civilia/projets/testedTools/gtfs-realtime-validator/pom.xml) has 3 errors
[ERROR]     Malformed POM /home/xavier/Documents/Civilia/projets/testedTools/gtfs-realtime-validator/pom.xml: Expected root element 'project' but found 'dependency' (position: START_TAG seen <dependency>... @1:13)  @ /home/xavier/Documents/Civilia/projets/testedTools/gtfs-realtime-validator/pom.xml, line 1, column 13 -> [Help 2]
[ERROR]     'modelVersion' is missing. @ line 1, column 13
[ERROR]     'modelVersion' is missing. @ line 1, column 13
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException

**Comment by jcpitre** [comment]
It looks like your pom.xml has errors in it. Can you provide it?

**Comment by civiliaInc** [comment]
It is the one provided on the README page:

<dependency>
  <groupId>org.mobilitydata</groupId>
  <artifactId>gtfs-realtime-validator-webapp</artifactId>
  <version>1.0.0-SNAPSHOT</version>
</dependency>

**Comment by jcpitre** [comment]
This was continued with a conversation with some back and forth on slack [here](https://mobilitydata-io.slack.com/archives/C3D321CKB/p1727271353269039).
The goal was to "run the validator once to measure the quality of a given feed".

You can use batch processing to do that. See instructions [here](https://github.com/MobilityData/gtfs-realtime-validator/tree/master/gtfs-realtime-validator-lib#batch-processing)

If you want to use the web validator, you can follow instructions [here](https://github.com/MobilityData/gtfs-realtime-validator?tab=readme-ov-file#run-the-webapp)
This will direct you to download from [this page](https://github.com/MobilityData/gtfs-realtime-validator/packages/1268975). You have to download the .jar file (gtfs-realtime-validator-webapp-1.0.0-20220223.003525-2.jar) then run it with
java -jar {JAR file name}  This will start a local web server that you can access with http://localhost:8080/

**Comment by jcpitre** [comment]
Closing this issue as an answer was supplied. 
If it's not satisfactory please reach out again.
