### ISSUE TITLE
Unable to open GTFS file - SSL config

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-realtime-validator#80]
**Issue by [mcplanner-zz](https://github.com/mcplanner-zz)**
_Nov 11, 2020_
_Originally opened as https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/389_

----

**Summary:** 

I'm getting a "(Download failed) error for this static .zip file, though I can download the file directly in the browser without issue.

**Steps to reproduce:** 

Ruths-MacBook-2:downloads ruthmiller$ java -Djsse.enableSNIExtension=false -jar gtfs-realtime-validator-webapp-1.0.0-SNAPSHOT.jar

https://www.modestoareaexpress.com/preview-gtfs.zip
http://max.availtec.com/InfoPoint/GTFS-Realtime.ashx?Type=VehiclePosition
http://max.availtec.com/InfoPoint/GTFS-Realtime.ashx?Type=Alert
http://max.availtec.com/InfoPoint/GTFS-Realtime.ashx?Type=Tripupdate

**Expected behavior:** 

I expected it to download the GTFS file.

**Observed behavior:** 

"Bad Request. Downloading static GTFS feed from provided Url failed."

**Platform:** 

MacOS Catalina 10.15.7
Java version: 11.0.5
Chrome version 86.0.4240.80

---
This there was a lot of back-and-forth comments on this issue, they weren't copied here. The bug was solved, and the label of this issue was changed to "docs". Go to the [original issue](https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/389) for more context on this bug.

**Comment by isabelle-dr** [comment]
**Comment by [barbeau](https://github.com/barbeau)**
_Nov 12, 2020_

----
@mcplanner Does this always happen every time you start validation on this feed?

If I start up the validator (using master branch within IntelliJ on Windows 10) and use the static GTFS and TripUpdate feeds above (unchecking "Run GTFS validation" and "Use shapes.txt for GTFS-realtime rules" to speed things up) it seems to work fine for me.

**Comment by isabelle-dr** [comment]
**Comment by [mcplanner-zz](https://github.com/mcplanner-zz)**
_Nov 12, 2020_

----
With both GTFS boxes unchecked, and running on each of the real time feeds
individually, I have been unable to get this static feed to work. I also
tried downloading it and using the local path, and that didn't work either.

**Comment by isabelle-dr** [comment]
**Comment by [barbeau](https://github.com/barbeau)**
_Nov 12, 2020_

----
Hmmm, ok, thanks. I'll have to test this further. I'm running on Windows 10 from IntelliJ so maybe it's platform-specific or an issue using the release JAR instead of the development environment.

**Comment by barbeau** [comment]
As mentioned in PR https://github.com/MobilityData/gtfs-realtime-validator/pull/85, from recent testing on JDK 11 (`java version "11.0.12" 2021-07-20 LTS`) and JDK 17 (`17.0.2`) the SSL issue no longer seems to exist and we don't need special configuration for SSL in general for this project. As a result I'm closing this, but if someone runs into this issue again please feel free to re-open.
